### ISSUE TITLE
ModulNotFoundError

### ISSUE THREAD

**Issue by joe-eis** [sumanth107/Restoration-Colorization-Enhancement-of-Images#1]
Hello,

I'm using Xubntu 20.04 LTS with Python 3.8.10.
I have this problems:

`Traceback (most recent call last):
  File "detection.py", line 13, in <module>
    from colorizers import *
ModuleNotFoundError: No module named 'colorizers'
`
The modul colorizer is in pip3 not available. Only colorize, but this is not the sulution.

`ModuleNotFoundError: No module named 'Face_Enhancement'
`
pip3 is not find this modul.

* * *

I don't understand this message,
`./checkpoints/restoration/VAE_A_quality/latest_net_G.pth not exists yet!
`
```
ll ./checkpoints/restoration/VAE_A_quality/

-rw-rw-r-- 1 joern joern  3498887 Sep  9  2020 latest_net_G.pth

```
`

**Comment by sumanth107** [comment]
Hello,
Thanks for writing.

> `ModuleNotFoundError`

The [colorizers module](https://github.com/sumanth107/Restoration-Colorization-Enhancement-of-Images/tree/main/colorizers) used in this project is not related to the colorizer module available in pip3. This module was created for the ease of use in this project. It can be found here : [colorizers module](https://github.com/sumanth107/Restoration-Colorization-Enhancement-of-Images/tree/main/colorizers)
Please download the whole repo and you will be able to import the module from the above link.

> `./checkpoints/restoration/VAE_A_quality/latest_net_G.pth not exists yet!`

Before being able to successfully run the project, certain pre-trained model must be downloaded and included in the appropriate directories. The above error is the consequence of the absence of one such pre-trained model.  The instructions for the same can be found in the [Readme.txt](https://drive.google.com/drive/u/1/folders/1Q6500KcgQls10Ljlte96HZYFEqSHszoH) in the following [link](https://drive.google.com/drive/u/1/folders/1Q6500KcgQls10Ljlte96HZYFEqSHszoH).
